.PHONY: all clean format

all:
	$(MAKE) -C ex1/ecoute_active
	$(MAKE) -C ex1/ecoute_passive

	
clean:
	$(MAKE) -C ex1/ecoute_active clean
	$(MAKE) -C ex1/ecoute_passive clean 


format : 
	$(MAKE) -C ex1/ecoute_active format
	$(MAKE) -C ex1/ecoute_passive format


