.PHONY: all clean format

all:
	$(MAKE) -C ex1/ecoute_active
	$(MAKE) -C ex1/ecoute_passive
	$(MAKE) -C ex2
	$(MAKE) -C ex3
	$(MAKE) -C ex4
	$(MAKE) -C ex5

	
clean:
	$(MAKE) -C ex1/ecoute_active clean
	$(MAKE) -C ex1/ecoute_passive clean 
	$(MAKE) -C ex2 clean
	$(MAKE) -C ex3 clean
	$(MAKE) -C ex4 clean
	$(MAKE) -C ex5 clean


format : 
	$(MAKE) -C ex1/ecoute_active format
	$(MAKE) -C ex1/ecoute_passive format
	$(MAKE) -C ex2 format
	$(MAKE) -C ex3 format 
	$(MAKE) -C ex4 format
	$(MAKE) -C ex5 format 


