.PHONY: all clean

all:
	$(MAKE) -C ex1
	$(MAKE) -C ex2
	$(MAKE) -C ex3
	$(MAKE) -C ex4
	$(MAKE) -C ex5/read_int
	$(MAKE) -C ex5/write_int

clean:
	$(MAKE) -C ex1 clean
	$(MAKE) -C ex2 clean
	$(MAKE) -C ex3 clean
	$(MAKE) -C ex4 clean
	$(MAKE) -C ex5/read_int clean
	$(MAKE) -C ex5/write_int clean
	
format : 
	$(MAKE) -C ex1 format
	$(MAKE) -C ex2 format
	$(MAKE) -C ex3 format
	$(MAKE) -C ex4 format
	$(MAKE) -C ex5/read_int format
	$(MAKE) -C ex5/write_int format
