.PHONY: all 

all:
	$(MAKE) -C ex1
	$(MAKE) -C ex2

.phony: clean format sanitizers

clean:
	$(MAKE) -C ex1 clean
	$(MAKE) -C ex2 clean
	
format : 
	$(MAKE) -C ex1 format
	$(MAKE) -C ex2 format

sanitizers : 
	$(MAKE) -C ex1 sanitizers
	$(MAKE) -C ex2 sanitizers
