.PHONY: all clean format

all:
	$(MAKE) -C ex1/pipe_a
	$(MAKE) -C ex1/pipe_b
	$(MAKE) -C ex1/pipe_c
	
clean:
	$(MAKE) -C ex1/pipe_a clean
	$(MAKE) -C ex1/pipe_b clean 
	$(MAKE) -C ex1/pipe_c clean

format : 
	$(MAKE) -C ex1/pipe_a format
	$(MAKE) -C ex1/pipe_b format
	$(MAKE) -C ex1/pipe_c format

